// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 002_diets.sql

package database

import (
	"context"
)

const createDiet = `-- name: CreateDiet :one
Insert into diets ( diet_type, user_id )
Values ( ?, ? )
Returning id, diet_type, user_id
`

type CreateDietParams struct {
	DietType string
	UserID   int64
}

func (q *Queries) CreateDiet(ctx context.Context, arg CreateDietParams) (Diet, error) {
	row := q.db.QueryRowContext(ctx, createDiet, arg.DietType, arg.UserID)
	var i Diet
	err := row.Scan(&i.ID, &i.DietType, &i.UserID)
	return i, err
}
