// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 003_weigh_ins.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createWeighIn = `-- name: CreateWeighIn :one
Insert into weigh_ins (created_at, updated_at, weight, weight_unit, log_date, log_date_display, note, cheated, alcohol, weigh_in_diet, user_id)
Values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Returning id, created_at, updated_at, weight, weight_unit, log_date, note, cheated, alcohol, weigh_in_diet, user_id, log_date_display
`

type CreateWeighInParams struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Weight         int64
	WeightUnit     string
	LogDate        time.Time
	LogDateDisplay string
	Note           sql.NullString
	Cheated        bool
	Alcohol        bool
	WeighInDiet    string
	UserID         int64
}

func (q *Queries) CreateWeighIn(ctx context.Context, arg CreateWeighInParams) (WeighIn, error) {
	row := q.db.QueryRowContext(ctx, createWeighIn,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Weight,
		arg.WeightUnit,
		arg.LogDate,
		arg.LogDateDisplay,
		arg.Note,
		arg.Cheated,
		arg.Alcohol,
		arg.WeighInDiet,
		arg.UserID,
	)
	var i WeighIn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.WeightUnit,
		&i.LogDate,
		&i.Note,
		&i.Cheated,
		&i.Alcohol,
		&i.WeighInDiet,
		&i.UserID,
		&i.LogDateDisplay,
	)
	return i, err
}

const deleteWeighIn = `-- name: DeleteWeighIn :exec
Delete from weigh_ins
Where id = ?
`

func (q *Queries) DeleteWeighIn(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWeighIn, id)
	return err
}

const getWeighInById = `-- name: GetWeighInById :one
Select id, created_at, updated_at, weight, weight_unit, log_date, note, cheated, alcohol, weigh_in_diet, user_id, log_date_display from weigh_ins
where id = ?
`

func (q *Queries) GetWeighInById(ctx context.Context, id int64) (WeighIn, error) {
	row := q.db.QueryRowContext(ctx, getWeighInById, id)
	var i WeighIn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.WeightUnit,
		&i.LogDate,
		&i.Note,
		&i.Cheated,
		&i.Alcohol,
		&i.WeighInDiet,
		&i.UserID,
		&i.LogDateDisplay,
	)
	return i, err
}

const getWeighInsByUser = `-- name: GetWeighInsByUser :many
Select id, created_at, updated_at, weight, weight_unit, log_date, note, cheated, alcohol, weigh_in_diet, user_id, log_date_display from weigh_ins
where user_id = ?
order by log_date asc
`

func (q *Queries) GetWeighInsByUser(ctx context.Context, userID int64) ([]WeighIn, error) {
	rows, err := q.db.QueryContext(ctx, getWeighInsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeighIn
	for rows.Next() {
		var i WeighIn
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Weight,
			&i.WeightUnit,
			&i.LogDate,
			&i.Note,
			&i.Cheated,
			&i.Alcohol,
			&i.WeighInDiet,
			&i.UserID,
			&i.LogDateDisplay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeightChartDataByUser = `-- name: GetWeightChartDataByUser :many
Select log_date, weight, weigh_in_diet from weigh_ins
where user_id = ? and log_date >= ?
order by log_date
`

type GetWeightChartDataByUserParams struct {
	UserID  int64
	LogDate time.Time
}

type GetWeightChartDataByUserRow struct {
	LogDate     time.Time
	Weight      int64
	WeighInDiet string
}

func (q *Queries) GetWeightChartDataByUser(ctx context.Context, arg GetWeightChartDataByUserParams) ([]GetWeightChartDataByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeightChartDataByUser, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeightChartDataByUserRow
	for rows.Next() {
		var i GetWeightChartDataByUserRow
		if err := rows.Scan(&i.LogDate, &i.Weight, &i.WeighInDiet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeighIn = `-- name: UpdateWeighIn :exec
Update weigh_ins
Set updated_at = ?, weight = ?, weight_unit = ?, log_date = ?, log_date_display = ?, note = ?, cheated = ?, alcohol = ?,
weigh_in_diet = ?
Where id = ?
`

type UpdateWeighInParams struct {
	UpdatedAt      time.Time
	Weight         int64
	WeightUnit     string
	LogDate        time.Time
	LogDateDisplay string
	Note           sql.NullString
	Cheated        bool
	Alcohol        bool
	WeighInDiet    string
	ID             int64
}

func (q *Queries) UpdateWeighIn(ctx context.Context, arg UpdateWeighInParams) error {
	_, err := q.db.ExecContext(ctx, updateWeighIn,
		arg.UpdatedAt,
		arg.Weight,
		arg.WeightUnit,
		arg.LogDate,
		arg.LogDateDisplay,
		arg.Note,
		arg.Cheated,
		arg.Alcohol,
		arg.WeighInDiet,
		arg.ID,
	)
	return err
}
