// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 003_weigh_ins.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createWeighIn = `-- name: CreateWeighIn :one
Insert into weigh_ins (created_at, updated_at, weight, weight_unit, log_date, note, cheated, alcohol, weigh_in_diet)
Values ( ?, ?, ?, ?, ?, ?, ?, ?, ?)
Returning id, created_at, updated_at, weight, weight_unit, log_date, note, cheated, alcohol, weigh_in_diet
`

type CreateWeighInParams struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Weight      int64
	WeightUnit  string
	LogDate     time.Time
	Note        sql.NullString
	Cheated     bool
	Alcohol     bool
	WeighInDiet string
}

func (q *Queries) CreateWeighIn(ctx context.Context, arg CreateWeighInParams) (WeighIn, error) {
	row := q.db.QueryRowContext(ctx, createWeighIn,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Weight,
		arg.WeightUnit,
		arg.LogDate,
		arg.Note,
		arg.Cheated,
		arg.Alcohol,
		arg.WeighInDiet,
	)
	var i WeighIn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Weight,
		&i.WeightUnit,
		&i.LogDate,
		&i.Note,
		&i.Cheated,
		&i.Alcohol,
		&i.WeighInDiet,
	)
	return i, err
}
