// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Diet struct {
	ID       int64
	DietType string
	UserID   int64
}

type User struct {
	ID             int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	AccessToken    string
	FullName       sql.NullString
	Provider       sql.NullString
	WeightUnit     interface{}
	Username       sql.NullString
	StartingWeight sql.NullInt64
}

type WeighIn struct {
	ID             int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Weight         int64
	WeightUnit     string
	LogDate        time.Time
	Note           sql.NullString
	Cheated        bool
	Alcohol        bool
	WeighInDiet    string
	UserID         int64
	LogDateDisplay string
}
