// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Diet struct {
	ID       int64
	DietType sql.NullString
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     sql.NullString
}

type WeighIn struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Weight      sql.NullInt64
	WeightUnit  sql.NullString
	LogDate     time.Time
	Note        sql.NullString
	Cheated     bool
	Alcohol     bool
	WeighInDiet sql.NullString
}
