
services:
  app:
    image: weigh_in:latest
    container_name: weigh_in
    volumes:
      - sqlite_data:/app/data  # Mount volume inside container
    ports:
      - "8080:8080"  # Example port mapping, adjust as needed
    env_file:
      - .env


volumes:
  sqlite_data:
